import {AfterViewInit, Component, ElementRef, OnInit, ViewChild} from '@angular/core';
import {Users} from "./models/users";
import {LeaderboardService} from "./services/leaderboard.service";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  @ViewChild('input') input: any;
  words: any[] = []; // English Words
  currentCount: number = 0; // Current Word Index
  type = ''; // Input Model
  transformPx: number = 0; // Transform Px Degree
  wrongCount: number = 0; // Wrong Count
  setInterval: any; //SetInterval Function For Global Spaces
  setIntervalChangeSpeed: any; //SetInterval Function For Global Spaces
  timeout: number = 30; // SetInterval Speed
  leaderboard: Users[];
  username = '';
  time: number = 0;
  timeInterval: any;

constructor(private leaderboardService: LeaderboardService) { }

  startGame() {
    this.setInterval = setInterval(() => {
      this.input.nativeElement.focus();
      this.transformPx = this.transformPx - 1;
    }, this.timeout);

    this.setIntervalChangeSpeed = setInterval(()=>{
      this.changeSpeed();
    }, 2000);

    if(this.time === 0){
      this.timeInterval = setInterval(()=>{
        this.time++;
        console.log(this.time);
      }, 1000);
    }
  }

  changeSpeed() {
   if(this.timeout !== 0){
     this.timeout = this.timeout - 2;
     clearInterval(this.setInterval);
     clearInterval(this.setIntervalChangeSpeed);
     this.startGame();
   }
  }

  finishGame() {
    clearInterval(this.timeInterval);
    if (this.username !== '') {
      this.leaderboardService.addUser(this.username, this.time,this.currentCount - this.wrongCount);
    }
    this.type = '';
    this.username = '';
    this.currentCount = 0;
    clearInterval(this.setInterval);
    clearInterval(this.setIntervalChangeSpeed);
    this.words.forEach(word => {
      word.status = true;
    });
    this.transformPx = 0;
    this.wrongCount = 0;
    this.timeout = 30;
  }

  keyPressAlphaNumeric(event: any) {
    const inp = String.fromCharCode(event.keyCode);
    if (/[a-zA-Z0-9]/.test(inp)) {
      return true;
    } else {
      if(event.code === 'Backspace'){
        return true;
      }else{
        event.preventDefault();
        return false;
      }
    }
  }

  inputChange(event: any) {
    const currentWord = this.words[this.currentCount];
    if (currentWord.name.startsWith(this.type)) {
      if (this.type === currentWord.name && event.code === 'Space') {
        this.words[this.currentCount].status = false;
        this.currentCount++;
        this.type = '';
      } else {
        this.words[this.currentCount].status = true;
      }
    } else {
      this.words[this.currentCount].status = null;
      if (this.type.length > 0 && event.code === 'Space') {
        this.words[this.currentCount].status = null;
        this.currentCount++;
        this.wrongCount++;
        this.type = '';
        if (this.wrongCount === 3) {
          alert('Game Over! Your Score is ' + (this.currentCount - this.wrongCount));
          this.finishGame();
        }
      }
    }
  }

  ngOnInit() {
    this.leaderboardService.getLeaderboard().subscribe((data) => {
      this.leaderboard = data;
    });
    this.words.push({name: 'loss', status: true}); // true- yazılmamış | false- yazılmış | null- hatalı
    this.words.push({name: 'charge', status: true});
    this.words.push({name: 'trouble', status: true});
    this.words.push({name: 'table', status: true});
    this.words.push({name: 'price', status: true});
    this.words.push({name: 'last', status: true});
    this.words.push({name: 'thousand', status: true});
    this.words.push({name: 'defense', status: true});
    this.words.push({name: 'situation', status: true});
    this.words.push({name: 'require', status: true});
    this.words.push({name: 'field', status: true});
    this.words.push({name: 'water', status: true});
    this.words.push({name: 'stage', status: true});
    this.words.push({name: 'painting', status: true});
    this.words.push({name: 'money', status: true});
    this.words.push({name: 'write', status: true});
    this.words.push({name: 'simply', status: true});
    this.words.push({name: 'then', status: true});
    this.words.push({name: 'middle', status: true});
    this.words.push({name: 'green', status: true});
    this.words.push({name: 'truth', status: true});
    this.words.push({name: 'resource', status: true});
    this.words.push({name: 'draw', status: true});
    this.words.push({name: 'on', status: true});
    this.words.push({name: 'how', status: true});
    this.words.push({name: 'dog', status: true});
    this.words.push({name: 'cut', status: true});
    this.words.push({name: 'forget', status: true});
    this.words.push({name: 'social', status: true});
    this.words.push({name: 'very', status: true});
    this.words.push({name: 'according', status: true});
    this.words.push({name: 'seat', status: true});
    this.words.push({name: 'trade', status: true});
    this.words.push({name: 'maybe', status: true});
    this.words.push({name: 'early', status: true});
    this.words.push({name: 'article', status: true});
    this.words.push({name: 'challenge', status: true});
    this.words.push({name: 'federal', status: true});
    this.words.push({name: 'laugh', status: true});
    this.words.push({name: 'result', status: true});
    this.words.push({name: 'lead', status: true});
    this.words.push({name: 'piece', status: true});
    this.words.push({name: 'respond', status: true});
    this.words.push({name: 'play', status: true});
    this.words.push({name: 'help', status: true});
    this.words.push({name: 'close', status: true});
    this.words.push({name: 'offer', status: true});
    this.words.push({name: 'clear', status: true});
    this.words.push({name: 'out', status: true});
    this.words.push({name: 'expert', status: true});
    this.words.push({name: 'victim', status: true});
    this.words.push({name: 'trial', status: true});
    this.words.push({name: 'big', status: true});
    this.words.push({name: 'traditional', status: true});
    this.words.push({name: 'born', status: true});
    this.words.push({name: 'memory', status: true});
    this.words.push({name: 'sound', status: true});
    this.words.push({name: 'edge', status: true});
    this.words.push({name: 'especially', status: true});
    this.words.push({name: 'actually', status: true});
    this.words.push({name: 'teach', status: true});
    this.words.push({name: 'keep', status: true});
    this.words.push({name: 'rich', status: true});
    this.words.push({name: 'life', status: true});
    this.words.push({name: 'should', status: true});
    this.words.push({name: 'politics', status: true});
    this.words.push({name: 'western', status: true});
    this.words.push({name: 'start', status: true});
    this.words.push({name: 'idea', status: true});
    this.words.push({name: 'themselves', status: true});
    this.words.push({name: 'serve', status: true});
    this.words.push({name: 'maintain', status: true});
    this.words.push({name: 'leader', status: true});
    this.words.push({name: 'country', status: true});
    this.words.push({name: 'public', status: true});
    this.words.push({name: 'shoulder', status: true});
    this.words.push({name: 'protect', status: true});
    this.words.push({name: 'attack', status: true});
    this.words.push({name: 'add', status: true});
    this.words.push({name: 'usually', status: true});
    this.words.push({name: 'picture', status: true});
    this.words.push({name: 'report', status: true});
    this.words.push({name: 'fire', status: true});
    this.words.push({name: 'above', status: true});
    this.words.push({name: 'agreement', status: true});
    this.words.push({name: 'fill', status: true});
    this.words.push({name: 'weight', status: true});
    this.words.push({name: 'who', status: true});
    this.words.push({name: 'although', status: true});
    this.words.push({name: 'I', status: true});
    this.words.push({name: 'order', status: true});
    this.words.push({name: 'education', status: true});
    this.words.push({name: 'court', status: true});
    this.words.push({name: 'magazine', status: true});
    this.words.push({name: 'writer', status: true});
    this.words.push({name: 'both', status: true});
    this.words.push({name: 'huge', status: true});
    this.words.push({name: 'owner', status: true});
    this.words.push({name: 'lie', status: true});
    this.words.push({name: 'that', status: true});
    this.words.push({name: 'culture', status: true});
    this.words.push({name: 'film', status: true});
    this.words.push({name: 'reduce', status: true});
    this.words.push({name: 'professional', status: true});
    this.words.push({name: 'notice', status: true});
    this.words.push({name: 'present', status: true});
    this.words.push({name: 'soon', status: true});
    this.words.push({name: 'scene', status: true});
    this.words.push({name: 'environment', status: true});
    this.words.push({name: 'career', status: true});
    this.words.push({name: 'certainly', status: true});
    this.words.push({name: 'off', status: true});
    this.words.push({name: 'forward', status: true});
    this.words.push({name: 'record', status: true});
    this.words.push({name: 'market', status: true});
    this.words.push({name: 'change', status: true});
    this.words.push({name: 'establish', status: true});
    this.words.push({name: 'against', status: true});
    this.words.push({name: 'choice', status: true});
    this.words.push({name: 'yard', status: true});
    this.words.push({name: 'claim', status: true});
    this.words.push({name: 'create', status: true});
    this.words.push({name: 'former', status: true});
    this.words.push({name: 'imagine', status: true});
    this.words.push({name: 'indicate', status: true});
    this.words.push({name: 'specific', status: true});
    this.words.push({name: 'garden', status: true});
    this.words.push({name: 'detail', status: true});
    this.words.push({name: 'wall', status: true});
    this.words.push({name: 'minute', status: true});
    this.words.push({name: 'after', status: true});
    this.words.push({name: 'sexual', status: true});
    this.words.push({name: 'data', status: true});
    this.words.push({name: 'they', status: true});
    this.words.push({name: 'act', status: true});
    this.words.push({name: 'health', status: true});
    this.words.push({name: 'leg', status: true});
    this.words.push({name: 'character', status: true});
    this.words.push({name: 'teacher', status: true});
    this.words.push({name: 'world', status: true});
    this.words.push({name: 'boy', status: true});
    this.words.push({name: 'summer', status: true});
    this.words.push({name: 'place', status: true});
    this.words.push({name: 'service', status: true});
    this.words.push({name: 'reveal', status: true});
    this.words.push({name: 'its', status: true});
    this.words.push({name: 'free', status: true});
    this.words.push({name: 'drop', status: true});
    this.words.push({name: 'fine', status: true});
    this.words.push({name: 'behind', status: true});
    this.words.push({name: 'bring', status: true});
    this.words.push({name: 'face', status: true});
    this.words.push({name: 'late', status: true});
    this.words.push({name: 'myself', status: true});
    this.words.push({name: 'institution', status: true});
    this.words.push({name: 'feeling', status: true});
    this.words.push({name: 'police', status: true});
    this.words.push({name: 'lay', status: true});
    this.words.push({name: 'decision', status: true});
    this.words.push({name: 'range', status: true});
    this.words.push({name: 'live', status: true});
    this.words.push({name: 'machine', status: true});
    this.words.push({name: 'gas', status: true});
    this.words.push({name: 'government', status: true});
    this.words.push({name: 'item', status: true});
    this.words.push({name: 'would', status: true});
    this.words.push({name: 'skill', status: true});
    this.words.push({name: 'in', status: true});
    this.words.push({name: 'remain', status: true});
    this.words.push({name: 'PM', status: true});
    this.words.push({name: 'between', status: true});
    this.words.push({name: 'whatever', status: true});
    this.words.push({name: 'always', status: true});
    this.words.push({name: 'up', status: true});
    this.words.push({name: 'remember', status: true});
    this.words.push({name: 'million', status: true});
    this.words.push({name: 'or', status: true});
    this.words.push({name: 'group', status: true});
    this.words.push({name: 'where', status: true});
    this.words.push({name: 'tend', status: true});
    this.words.push({name: 'force', status: true});
    this.words.push({name: 'yeah', status: true});
    this.words.push({name: 'well', status: true});
    this.words.push({name: 'common', status: true});
    this.words.push({name: 'growth', status: true});
    this.words.push({name: 'able', status: true});
    this.words.push({name: 'debate', status: true});
    this.words.push({name: 'consider', status: true});
    this.words.push({name: 'team', status: true});
    this.words.push({name: 'right', status: true});
    this.words.push({name: 'TV', status: true});
    this.words.push({name: 'hundred', status: true});
    this.words.push({name: 'else', status: true});
    this.words.push({name: 'prevent', status: true});
    this.words.push({name: 'yet', status: true});
    this.words.push({name: 'doctor', status: true});
    this.words.push({name: 'same', status: true});
    this.words.push({name: 'wonder', status: true});
    this.words.push({name: 'political', status: true});
    this.words.push({name: 'best', status: true});
    this.words.push({name: 'decade', status: true});
    this.words.push({name: 'room', status: true});
    this.words.push({name: 'also', status: true});
    this.words.push({name: 'individual', status: true});
    this.words.push({name: 'too', status: true});
    this.words.push({name: 'Republican', status: true});
    this.words.push({name: 'college', status: true});
    this.words.push({name: 'camera', status: true});
    this.words.push({name: 'mention', status: true});
    this.words.push({name: 'visit', status: true});
    this.words.push({name: 'reason', status: true});
    this.words.push({name: 'itself', status: true});
    this.words.push({name: 'his', status: true});
    this.words.push({name: 'newspaper', status: true});
    this.words.push({name: 'north', status: true});
    this.words.push({name: 'box', status: true});
    this.words.push({name: 'this', status: true});
    this.words.push({name: 'involve', status: true});
    this.words.push({name: 'down', status: true});
    this.words.push({name: 'risk', status: true});
    this.words.push({name: 'interest', status: true});
    this.words.push({name: 'Congress', status: true});
    this.words.push({name: 'provide', status: true});
    this.words.push({name: 'consumer', status: true});
    this.words.push({name: 'foot', status: true});
    this.words.push({name: 'something', status: true});
    this.words.push({name: 'yes', status: true});
    this.words.push({name: 'financial', status: true});
    this.words.push({name: 'serious', status: true});
    this.words.push({name: 'word', status: true});
    this.words.push({name: 'society', status: true});
    this.words.push({name: 'evidence', status: true});
    this.words.push({name: 'animal', status: true});
    this.words.push({name: 'hold', status: true});
    this.words.push({name: 'east', status: true});
    this.words.push({name: 'can', status: true});
    this.words.push({name: 'the', status: true});
    this.words.push({name: 'rise', status: true});
    this.words.push({name: 'save', status: true});
    this.words.push({name: 'American', status: true});
    this.words.push({name: 'hour', status: true});
    this.words.push({name: 'mouth', status: true});
    this.words.push({name: 'short', status: true});
    this.words.push({name: 'light', status: true});
    this.words.push({name: 'when', status: true});
    this.words.push({name: 'instead', status: true});
    this.words.push({name: 'those', status: true});
    this.words.push({name: 'occur', status: true});
    this.words.push({name: 'special', status: true});
    this.words.push({name: 'every', status: true});
    this.words.push({name: 'someone', status: true});
    this.words.push({name: 'inside', status: true});
    this.words.push({name: 'industry', status: true});
    this.words.push({name: 'successful', status: true});
    this.words.push({name: 'deal', status: true});
    this.words.push({name: 'nor', status: true});
    this.words.push({name: 'agree', status: true});
    this.words.push({name: 'few', status: true});
    this.words.push({name: 'include', status: true});
    this.words.push({name: 'response', status: true});
    this.words.push({name: 'if', status: true});
    this.words.push({name: 'just', status: true});
    this.words.push({name: 'story', status: true});
    this.words.push({name: 'card', status: true});
    this.words.push({name: 'coach', status: true});
    this.words.push({name: 'responsibility', status: true});
    this.words.push({name: 'partner', status: true});
    this.words.push({name: 'know', status: true});
    this.words.push({name: 'cause', status: true});
    this.words.push({name: 'treatment', status: true});
    this.words.push({name: 'real', status: true});
    this.words.push({name: 'job', status: true});
    this.words.push({name: 'lot', status: true});
    this.words.push({name: 'least', status: true});
    this.words.push({name: 'them', status: true});
    this.words.push({name: 'site', status: true});
    this.words.push({name: 'by', status: true});
    this.words.push({name: 'listen', status: true});
    this.words.push({name: 'far', status: true});
    this.words.push({name: 'study', status: true});
    this.words.push({name: 'call', status: true});
    this.words.push({name: 'despite', status: true});
    this.words.push({name: 'environmental', status: true});
    this.words.push({name: 'only', status: true});
    this.words.push({name: 'quite', status: true});
    this.words.push({name: 'ability', status: true});
    this.words.push({name: 'without', status: true});
    this.words.push({name: 'answer', status: true});
    this.words.push({name: 'cost', status: true});
    this.words.push({name: 'design', status: true});
    this.words.push({name: 'agent', status: true});
    this.words.push({name: 'get', status: true});
    this.words.push({name: 'might', status: true});
    this.words.push({name: 'tax', status: true});
    this.words.push({name: 'six', status: true});
    this.words.push({name: 'democratic', status: true});
    this.words.push({name: 'recent', status: true});
    this.words.push({name: 'executive', status: true});
    this.words.push({name: 'mission', status: true});
    this.words.push({name: 'concern', status: true});
    this.words.push({name: 'one', status: true});
    this.words.push({name: 'all', status: true});
    this.words.push({name: 'voice', status: true});
    this.words.push({name: 'for', status: true});
    this.words.push({name: 'total', status: true});
    this.words.push({name: 'woman', status: true});
    this.words.push({name: 'leave', status: true});
    this.words.push({name: 'stay', status: true});
    this.words.push({name: 'plan', status: true});
    this.words.push({name: 'tree', status: true});
    this.words.push({name: 'high', status: true});
    this.words.push({name: 'talk', status: true});
    this.words.push({name: 'fear', status: true});
    this.words.push({name: 'do', status: true});
    this.words.push({name: 'project', status: true});
    this.words.push({name: 'window', status: true});
    this.words.push({name: 'pay', status: true});
    this.words.push({name: 'time', status: true});
    this.words.push({name: 'rest', status: true});
    this.words.push({name: 'recognize', status: true});
    this.words.push({name: 'kind', status: true});
    this.words.push({name: 'value', status: true});
    this.words.push({name: 'dark', status: true});
    this.words.push({name: 'sing', status: true});
    this.words.push({name: 'beautiful', status: true});
    this.words.push({name: 'power', status: true});
    this.words.push({name: 'movie', status: true});
    this.words.push({name: 'everybody', status: true});
    this.words.push({name: 'your', status: true});
    this.words.push({name: 'physical', status: true});
    this.words.push({name: 'fact', status: true});
    this.words.push({name: 'score', status: true});
    this.words.push({name: 'husband', status: true});
    this.words.push({name: 'marriage', status: true});
    this.words.push({name: 'way', status: true});
    this.words.push({name: 'move', status: true});
    this.words.push({name: 'building', status: true});
    this.words.push({name: 'us', status: true});
    this.words.push({name: 'none', status: true});
    this.words.push({name: 'event', status: true});
    this.words.push({name: 'fail', status: true});
    this.words.push({name: 'exist', status: true});
    this.words.push({name: 'Mr', status: true});
    this.words.push({name: 'economy', status: true});
    this.words.push({name: 'quickly', status: true});
    this.words.push({name: 'street', status: true});
    this.words.push({name: 'artist', status: true});
    this.words.push({name: 'him', status: true});
    this.words.push({name: 'television', status: true});
    this.words.push({name: 'station', status: true});
    this.words.push({name: 'whom', status: true});
    this.words.push({name: 'wear', status: true});
    this.words.push({name: 'figure', status: true});
    this.words.push({name: 'meeting', status: true});
    this.words.push({name: 'finish', status: true});
    this.words.push({name: 'reflect', status: true});
    this.words.push({name: 'music', status: true});
    this.words.push({name: 'mind', status: true});
    this.words.push({name: 'structure', status: true});
    this.words.push({name: 'person', status: true});
    this.words.push({name: 'three', status: true});
    this.words.push({name: 'scientist', status: true});
    this.words.push({name: 'wind', status: true});
    this.words.push({name: 'research', status: true});
    this.words.push({name: 'let', status: true});
    this.words.push({name: 'shot', status: true});
    this.words.push({name: 'security', status: true});
    this.words.push({name: 'explain', status: true});
    this.words.push({name: 'everything', status: true});
    this.words.push({name: 'director', status: true});
    this.words.push({name: 'through', status: true});
    this.words.push({name: 'while', status: true});
    this.words.push({name: 'rate', status: true});
    this.words.push({name: 'wrong', status: true});
    this.words.push({name: 'suggest', status: true});
    this.words.push({name: 'strong', status: true});
    this.words.push({name: 'tough', status: true});
    this.words.push({name: 'effect', status: true});
    this.words.push({name: 'material', status: true});
    this.words.push({name: 'check', status: true});
    this.words.push({name: 'hard', status: true});
    this.words.push({name: 'hang', status: true});
    this.words.push({name: 'past', status: true});
    this.words.push({name: 'office', status: true});
    this.words.push({name: 'pick', status: true});
    this.words.push({name: 'die', status: true});
    this.words.push({name: 'difference', status: true});
    this.words.push({name: 'personal', status: true});
    this.words.push({name: 'news', status: true});
    this.words.push({name: 'certain', status: true});
    this.words.push({name: 'account', status: true});
    this.words.push({name: 'available', status: true});
    this.words.push({name: 'good', status: true});
    this.words.push({name: 'threat', status: true});
    this.words.push({name: 'thus', status: true});
    this.words.push({name: 'enjoy', status: true});
    this.words.push({name: 'like', status: true});
    this.words.push({name: 'prove', status: true});
    this.words.push({name: 'new', status: true});
    this.words.push({name: 'really', status: true});
    this.words.push({name: 'meet', status: true});
    this.words.push({name: 'go', status: true});
    this.words.push({name: 'left', status: true});
    this.words.push({name: 'and', status: true});
    this.words.push({name: 'pretty', status: true});
    this.words.push({name: 'foreign', status: true});
    this.words.push({name: 'join', status: true});
    this.words.push({name: 'opportunity', status: true});
    this.words.push({name: 'identify', status: true});
    this.words.push({name: 'various', status: true});
    this.words.push({name: 'case', status: true});
    this.words.push({name: 'official', status: true});
    this.words.push({name: 'oh', status: true});
    this.words.push({name: 'production', status: true});
    this.words.push({name: 'we', status: true});
    this.words.push({name: 'human', status: true});
    this.words.push({name: 'direction', status: true});
    this.words.push({name: 'property', status: true});
    this.words.push({name: 'allow', status: true});
    this.words.push({name: 'finger', status: true});
    this.words.push({name: 'mean', status: true});
    this.words.push({name: 'address', status: true});
    this.words.push({name: 'because', status: true});
    this.words.push({name: 'parent', status: true});
    this.words.push({name: 'information', status: true});
    this.words.push({name: 'century', status: true});
    this.words.push({name: 'trip', status: true});
    this.words.push({name: 'conference', status: true});
    this.words.push({name: 'size', status: true});
    this.words.push({name: 'body', status: true});
    this.words.push({name: 'student', status: true});
    this.words.push({name: 'officer', status: true});
    this.words.push({name: 'alone', status: true});
    this.words.push({name: 'manager', status: true});
    this.words.push({name: 'represent', status: true});
    this.words.push({name: 'week', status: true});
    this.words.push({name: 'reach', status: true});
    this.words.push({name: 'hand', status: true});
    this.words.push({name: 'pull', status: true});
    this.words.push({name: 'any', status: true});
    this.words.push({name: 'note', status: true});
    this.words.push({name: 'try', status: true});
    this.words.push({name: 'knowledge', status: true});
    this.words.push({name: 'cultural', status: true});
    this.words.push({name: 'hotel', status: true});
    this.words.push({name: 'billion', status: true});
    this.words.push({name: 'number', status: true});
    this.words.push({name: 'eat', status: true});
    this.words.push({name: 'radio', status: true});
    this.words.push({name: 'difficult', status: true});
    this.words.push({name: 'determine', status: true});
    this.words.push({name: 'disease', status: true});
    this.words.push({name: 'child', status: true});
    this.words.push({name: 'option', status: true});
    this.words.push({name: 'daughter', status: true});
    this.words.push({name: 'analysis', status: true});
    this.words.push({name: 'legal', status: true});
    this.words.push({name: 'view', status: true});
    this.words.push({name: 'treat', status: true});
    this.words.push({name: 'end', status: true});
    this.words.push({name: 'couple', status: true});
    this.words.push({name: 'employee', status: true});
    this.words.push({name: 'nature', status: true});
    this.words.push({name: 'two', status: true});
    this.words.push({name: 'baby', status: true});
    this.words.push({name: 'deep', status: true});
    this.words.push({name: 'death', status: true});
    this.words.push({name: 'car', status: true});
    this.words.push({name: 'to', status: true});
    this.words.push({name: 'ahead', status: true});
    this.words.push({name: 'organization', status: true});
    this.words.push({name: 'floor', status: true});
    this.words.push({name: 'class', status: true});
    this.words.push({name: 'surface', status: true});
    this.words.push({name: 'look', status: true});
    this.words.push({name: 'accept', status: true});
    this.words.push({name: 'possible', status: true});
    this.words.push({name: 'citizen', status: true});
    this.words.push({name: 'turn', status: true});
    this.words.push({name: 'happy', status: true});
    this.words.push({name: 'course', status: true});
    this.words.push({name: 'head', status: true});
    this.words.push({name: 'including', status: true});
    this.words.push({name: 'space', status: true});
    this.words.push({name: 'series', status: true});
    this.words.push({name: 'pattern', status: true});
    this.words.push({name: 'effort', status: true});
    this.words.push({name: 'purpose', status: true});
    this.words.push({name: 'guess', status: true});
    this.words.push({name: 'standard', status: true});
    this.words.push({name: 'main', status: true});
    this.words.push({name: 'side', status: true});
    this.words.push({name: 'my', status: true});
    this.words.push({name: 'generation', status: true});
    this.words.push({name: 'energy', status: true});
    this.words.push({name: 'part', status: true});
    this.words.push({name: 'campaign', status: true});
    this.words.push({name: 'evening', status: true});
    this.words.push({name: 'raise', status: true});
    this.words.push({name: 'as', status: true});
    this.words.push({name: 'business', status: true});
    this.words.push({name: 'discuss', status: true});
    this.words.push({name: 'ok', status: true});
    this.words.push({name: 'prepare', status: true});
    this.words.push({name: 'believe', status: true});
    this.words.push({name: 'international', status: true});
    this.words.push({name: 'history', status: true});
    this.words.push({name: 'nation', status: true});
    this.words.push({name: 'product', status: true});
    this.words.push({name: 'point', status: true});
    this.words.push({name: 'strategy', status: true});
    this.words.push({name: 'professor', status: true});
    this.words.push({name: 'enter', status: true});
    this.words.push({name: 'ever', status: true});
    this.words.push({name: 'art', status: true});
    this.words.push({name: 'increase', status: true});
    this.words.push({name: 'problem', status: true});
    this.words.push({name: 'bad', status: true});
    this.words.push({name: 'war', status: true});
    this.words.push({name: 'worry', status: true});
    this.words.push({name: 'local', status: true});
    this.words.push({name: 'recently', status: true});
    this.words.push({name: 'once', status: true});
    this.words.push({name: 'third', status: true});
    this.words.push({name: 'less', status: true});
    this.words.push({name: 'message', status: true});
    this.words.push({name: 'buy', status: true});
    this.words.push({name: 'pass', status: true});
    this.words.push({name: 'more', status: true});
    this.words.push({name: 'hot', status: true});
    this.words.push({name: 'focus', status: true});
    this.words.push({name: 'ground', status: true});
    this.words.push({name: 'me', status: true});
    this.words.push({name: 'friend', status: true});
    this.words.push({name: 'father', status: true});
    this.words.push({name: 'success', status: true});
    this.words.push({name: 'house', status: true});
    this.words.push({name: 'today', status: true});
    this.words.push({name: 'central', status: true});
    this.words.push({name: 'safe', status: true});
    this.words.push({name: 'away', status: true});
    this.words.push({name: 'attorney', status: true});
    this.words.push({name: 'fly', status: true});
    this.words.push({name: 'great', status: true});
    this.words.push({name: 'much', status: true});
    this.words.push({name: 'reality', status: true});
    this.words.push({name: 'natural', status: true});
    this.words.push({name: 'cup', status: true});
    this.words.push({name: 'kitchen', status: true});
    this.words.push({name: 'national', status: true});
    this.words.push({name: 'throughout', status: true});
    this.words.push({name: 'system', status: true});
    this.words.push({name: 'future', status: true});
    this.words.push({name: 'outside', status: true});
    this.words.push({name: 'from', status: true});
    this.words.push({name: 'particular', status: true});
    this.words.push({name: 'ask', status: true});
    this.words.push({name: 'positive', status: true});
    this.words.push({name: 'need', status: true});
    this.words.push({name: 'cell', status: true});
    this.words.push({name: 'single', status: true});
    this.words.push({name: 'quality', status: true});
    this.words.push({name: 'her', status: true});
    this.words.push({name: 'thing', status: true});
    this.words.push({name: 'month', status: true});
    this.words.push({name: 'bed', status: true});
    this.words.push({name: 'interview', status: true});
    this.words.push({name: 'wide', status: true});
    this.words.push({name: 'top', status: true});
    this.words.push({name: 'star', status: true});
    this.words.push({name: 'crime', status: true});
    this.words.push({name: 'science', status: true});
    this.words.push({name: 'cancer', status: true});
    this.words.push({name: 'school', status: true});
    this.words.push({name: 'vote', status: true});
    this.words.push({name: 'region', status: true});
    this.words.push({name: 'eight', status: true});
    this.words.push({name: 'each', status: true});
    this.words.push({name: 'simple', status: true});
    this.words.push({name: 'fast', status: true});
    this.words.push({name: 'whose', status: true});
    this.words.push({name: 'book', status: true});
    this.words.push({name: 'be', status: true});
    this.words.push({name: 'you', status: true});
    this.words.push({name: 'together', status: true});
    this.words.push({name: 'already', status: true});
    this.words.push({name: 'example', status: true});
    this.words.push({name: 'medical', status: true});
    this.words.push({name: 'page', status: true});
    this.words.push({name: 'decide', status: true});
    this.words.push({name: 'yourself', status: true});
    this.words.push({name: 'now', status: true});
    this.words.push({name: 'perhaps', status: true});
    this.words.push({name: 'wait', status: true});
    this.words.push({name: 'think', status: true});
    this.words.push({name: 'relationship', status: true});
    this.words.push({name: 'majority', status: true});
    this.words.push({name: 'population', status: true});
    this.words.push({name: 'style', status: true});
    this.words.push({name: 'board', status: true});
    this.words.push({name: 'tell', status: true});
    this.words.push({name: 'second', status: true});
    this.words.push({name: 'area', status: true});
    this.words.push({name: 'west', status: true});
    this.words.push({name: 'pain', status: true});
    this.words.push({name: 'plant', status: true});
    this.words.push({name: 'return', status: true});
    this.words.push({name: 'what', status: true});
    this.words.push({name: 'several', status: true});
    this.words.push({name: 'lose', status: true});
    this.words.push({name: 'at', status: true});
    this.words.push({name: 'key', status: true});
    this.words.push({name: 'section', status: true});
    this.words.push({name: 'base', status: true});
    this.words.push({name: 'popular', status: true});
    this.words.push({name: 'realize', status: true});
    this.words.push({name: 'sign', status: true});
    this.words.push({name: 'next', status: true});
    this.words.push({name: 'program', status: true});
    this.words.push({name: 'role', status: true});
    this.words.push({name: 'eye', status: true});
    this.words.push({name: 'media', status: true});
    this.words.push({name: 'others', status: true});
    this.words.push({name: 'continue', status: true});
    this.words.push({name: 'audience', status: true});
    this.words.push({name: 'but', status: true});
    this.words.push({name: 'back', status: true});
    this.words.push({name: 'stock', status: true});
    this.words.push({name: 'she', status: true});
    this.words.push({name: 'poor', status: true});
    this.words.push({name: 'chance', status: true});
    this.words.push({name: 'however', status: true});
    this.words.push({name: 'store', status: true});
    this.words.push({name: 'development', status: true});
    this.words.push({name: 'most', status: true});
    this.words.push({name: 'center', status: true});
    this.words.push({name: 'put', status: true});
    this.words.push({name: 'stuff', status: true});
    this.words.push({name: 'rock', status: true});
    this.words.push({name: 'a', status: true});
    this.words.push({name: 'though', status: true});
    this.words.push({name: 'similar', status: true});
    this.words.push({name: 'their', status: true});
    this.words.push({name: 'attention', status: true});
    this.words.push({name: 'sport', status: true});
    this.words.push({name: 'oil', status: true});
    this.words.push({name: 'heat', status: true});
    this.words.push({name: 'degree', status: true});
    this.words.push({name: 'appear', status: true});
    this.words.push({name: 'cold', status: true});
    this.words.push({name: 'commercial', status: true});
    this.words.push({name: 'happen', status: true});
    this.words.push({name: 'private', status: true});
    this.words.push({name: 'day', status: true});
    this.words.push({name: 'form', status: true});
    this.words.push({name: 'benefit', status: true});
    this.words.push({name: 'home', status: true});
    this.words.push({name: 'suddenly', status: true});
    this.words.push({name: 'step', status: true});
    this.words.push({name: 'issue', status: true});
    this.words.push({name: 'experience', status: true});
    this.words.push({name: 'source', status: true});
    this.words.push({name: 'among', status: true});
    this.words.push({name: 'admit', status: true});
    this.words.push({name: 'nothing', status: true});
    this.words.push({name: 'final', status: true});
    this.words.push({name: 'within', status: true});
    this.words.push({name: 'bank', status: true});
    this.words.push({name: 'suffer', status: true});
    this.words.push({name: 'during', status: true});
    this.words.push({name: 'condition', status: true});
    this.words.push({name: 'nearly', status: true});
    this.words.push({name: 'he', status: true});
    this.words.push({name: 'later', status: true});
    this.words.push({name: 'dream', status: true});
    this.words.push({name: 'major', status: true});
    this.words.push({name: 'compare', status: true});
    this.words.push({name: 'speak', status: true});
    this.words.push({name: 'color', status: true});
    this.words.push({name: 'activity', status: true});
    this.words.push({name: 'assume', status: true});
    this.words.push({name: 'clearly', status: true});
    this.words.push({name: 'stop', status: true});
    this.words.push({name: 'learn', status: true});
    this.words.push({name: 'paper', status: true});
    this.words.push({name: 'discover', status: true});
    this.words.push({name: 'produce', status: true});
    this.words.push({name: 'soldier', status: true});
    this.words.push({name: 'build', status: true});
    this.words.push({name: 'law', status: true});
    this.words.push({name: 'arrive', status: true});
    this.words.push({name: 'finally', status: true});
    this.words.push({name: 'position', status: true});
    this.words.push({name: 'fall', status: true});
    this.words.push({name: 'begin', status: true});
    this.words.push({name: 'air', status: true});
    this.words.push({name: 'action', status: true});
    this.words.push({name: 'image', status: true});
    this.words.push({name: 'take', status: true});
    this.words.push({name: 'hope', status: true});
    this.words.push({name: 'miss', status: true});
    this.words.push({name: 'run', status: true});
    this.words.push({name: 'term', status: true});
    this.words.push({name: 'family', status: true});
    this.words.push({name: 'training', status: true});
    this.words.push({name: 'current', status: true});
    this.words.push({name: 'wish', status: true});
    this.words.push({name: 'anyone', status: true});
    this.words.push({name: 'white', status: true});
    this.words.push({name: 'period', status: true});
    this.words.push({name: 'sex', status: true});
    this.words.push({name: 'rule', status: true});
    this.words.push({name: 'somebody', status: true});
    this.words.push({name: 'model', status: true});
    this.words.push({name: 'peace', status: true});
    this.words.push({name: 'care', status: true});
    this.words.push({name: 'process', status: true});
    this.words.push({name: 'blue', status: true});
    this.words.push({name: 'ball', status: true});
    this.words.push({name: 'theory', status: true});
    this.words.push({name: 'rather', status: true});
    this.words.push({name: 'particularly', status: true});
    this.words.push({name: 'hospital', status: true});
    this.words.push({name: 'than', status: true});
    this.words.push({name: 'entire', status: true});
    this.words.push({name: 'sense', status: true});
    this.words.push({name: 'election', status: true});
    this.words.push({name: 'near', status: true});
    this.words.push({name: 'even', status: true});
    this.words.push({name: 'language', status: true});
    this.words.push({name: 'skin', status: true});
    this.words.push({name: 'economic', status: true});
    this.words.push({name: 'spring', status: true});
    this.words.push({name: 'church', status: true});
    this.words.push({name: 'develop', status: true});
    this.words.push({name: 'important', status: true});
    this.words.push({name: 'kill', status: true});
    this.words.push({name: 'exactly', status: true});
    this.words.push({name: 'hair', status: true});
    this.words.push({name: 'low', status: true});
    this.words.push({name: 'still', status: true});
    this.words.push({name: 'must', status: true});
    this.words.push({name: 'five', status: true});
    this.words.push({name: 'weapon', status: true});
    this.words.push({name: 'likely', status: true});
    this.words.push({name: 'choose', status: true});
    this.words.push({name: 'show', status: true});
    this.words.push({name: 'president', status: true});
    this.words.push({name: 'may', status: true});
    this.words.push({name: 'ago', status: true});
    this.words.push({name: 'interesting', status: true});
    this.words.push({name: 'arm', status: true});
    this.words.push({name: 'company', status: true});
    this.words.push({name: 'necessary', status: true});
    this.words.push({name: 'watch', status: true});
    this.words.push({name: 'love', status: true});
    this.words.push({name: 'into', status: true});
    this.words.push({name: 'beyond', status: true});
    this.words.push({name: 'morning', status: true});
    this.words.push({name: 'level', status: true});
    this.words.push({name: 'grow', status: true});
    this.words.push({name: 'toward', status: true});
    this.words.push({name: 'own', status: true});
    this.words.push({name: 'throw', status: true});
    this.words.push({name: 'find', status: true});
    this.words.push({name: 'walk', status: true});
    this.words.push({name: 'phone', status: true});
    this.words.push({name: 'girl', status: true});
    this.words.push({name: 'old', status: true});
    this.words.push({name: 'per', status: true});
    this.words.push({name: 'age', status: true});
    this.words.push({name: 'it', status: true});
    this.words.push({name: 'factor', status: true});
    this.words.push({name: 'food', status: true});
    this.words.push({name: 'there', status: true});
    this.words.push({name: 'avoid', status: true});
    this.words.push({name: 'candidate', status: true});
    this.words.push({name: 'speech', status: true});
    this.words.push({name: 'patient', status: true});
    this.words.push({name: 'describe', status: true});
    this.words.push({name: 'no', status: true});
    this.words.push({name: 'so', status: true});
    this.words.push({name: 'our', status: true});
    this.words.push({name: 'thank', status: true});
    this.words.push({name: 'young', status: true});
    this.words.push({name: 'better', status: true});
    this.words.push({name: 'since', status: true});
    this.words.push({name: 'across', status: true});
    this.words.push({name: 'almost', status: true});
    this.words.push({name: 'Democrat', status: true});
    this.words.push({name: 'expect', status: true});
    this.words.push({name: 'goal', status: true});
    this.words.push({name: 'often', status: true});
    this.words.push({name: 'subject', status: true});
    this.words.push({name: 'follow', status: true});
    this.words.push({name: 'southern', status: true});
    this.words.push({name: 'seek', status: true});
    this.words.push({name: 'enough', status: true});
    this.words.push({name: 'along', status: true});
    this.words.push({name: 'firm', status: true});
    this.words.push({name: 'manage', status: true});
    this.words.push({name: 'want', status: true});
    this.words.push({name: 'break', status: true});
    this.words.push({name: 'of', status: true});
    this.words.push({name: 'under', status: true});
    this.words.push({name: 'senior', status: true});
    this.words.push({name: 'many', status: true});
    this.words.push({name: 'sure', status: true});
    this.words.push({name: 'control', status: true});
    this.words.push({name: 'onto', status: true});
    this.words.push({name: 'customer', status: true});
    this.words.push({name: 'some', status: true});
    this.words.push({name: 'member', status: true});
    this.words.push({name: 'seem', status: true});
    this.words.push({name: 'why', status: true});
    this.words.push({name: 'general', status: true});
    this.words.push({name: 'matter', status: true});
    this.words.push({name: 'remove', status: true});
    this.words.push({name: 'four', status: true});
    this.words.push({name: 'sell', status: true});
    this.words.push({name: 'collection', status: true});
    this.words.push({name: 'year', status: true});
    this.words.push({name: 'fund', status: true});
    this.words.push({name: 'performance', status: true});
    this.words.push({name: 'understand', status: true});
    this.words.push({name: 'work', status: true});
    this.words.push({name: 'drug', status: true});
    this.words.push({name: 'sometimes', status: true});
    this.words.push({name: 'first', status: true});
    this.words.push({name: 'beat', status: true});
    this.words.push({name: 'discussion', status: true});
    this.words.push({name: 'nice', status: true});
    this.words.push({name: 'anything', status: true});
    this.words.push({name: 'staff', status: true});
    this.words.push({name: 'test', status: true});
    this.words.push({name: 'push', status: true});
    this.words.push({name: 'become', status: true});
    this.words.push({name: 'approach', status: true});
    this.words.push({name: 'give', status: true});
    this.words.push({name: 'technology', status: true});
    this.words.push({name: 'shoot', status: true});
    this.words.push({name: 'shake', status: true});
    this.words.push({name: 'sit', status: true});
    this.words.push({name: 'himself', status: true});
    this.words.push({name: 'about', status: true});
    this.words.push({name: 'herself', status: true});
    this.words.push({name: 'civil', status: true});
    this.words.push({name: 'ten', status: true});
    this.words.push({name: 'not', status: true});
    this.words.push({name: 'computer', status: true});
    this.words.push({name: 'amount', status: true});
    this.words.push({name: 'bill', status: true});
    this.words.push({name: 'name', status: true});
    this.words.push({name: 'ready', status: true});
    this.words.push({name: 'seven', status: true});
    this.words.push({name: 'practice', status: true});
    this.words.push({name: 'half', status: true});
    this.words.push({name: 'list', status: true});
    this.words.push({name: 'violence', status: true});
    this.words.push({name: 'sort', status: true});
    this.words.push({name: 'see', status: true});
    this.words.push({name: 'come', status: true});
    this.words.push({name: 'management', status: true});
    this.words.push({name: 'argue', status: true});
    this.words.push({name: 'military', status: true});
    this.words.push({name: 'player', status: true});
    this.words.push({name: 'fight', status: true});
    this.words.push({name: 'policy', status: true});
    this.words.push({name: 'affect', status: true});
    this.words.push({name: 'here', status: true});
    this.words.push({name: 'authority', status: true});
    this.words.push({name: 'these', status: true});
    this.words.push({name: 'moment', status: true});
    this.words.push({name: 'brother', status: true});
    this.words.push({name: 'heavy', status: true});
    this.words.push({name: 'carry', status: true});
    this.words.push({name: 'race', status: true});
    this.words.push({name: 'impact', status: true});
    this.words.push({name: 'modern', status: true});
    this.words.push({name: 'relate', status: true});
    this.words.push({name: 'whole', status: true});
    this.words.push({name: 'city', status: true});
    this.words.push({name: 'song', status: true});
    this.words.push({name: 'capital', status: true});
    this.words.push({name: 'hear', status: true});
    this.words.push({name: 'hit', status: true});
    this.words.push({name: 'different', status: true});
    this.words.push({name: 'until', status: true});
    this.words.push({name: 'season', status: true});
    this.words.push({name: 'catch', status: true});
    this.words.push({name: 'south', status: true});
    this.words.push({name: 'true', status: true});
    this.words.push({name: 'could', status: true});
    this.words.push({name: 'everyone', status: true});
    this.words.push({name: 'method', status: true});
    this.words.push({name: 'drive', status: true});
    this.words.push({name: 'land', status: true});
    this.words.push({name: 'worker', status: true});
    this.words.push({name: 'letter', status: true});
    this.words.push({name: 'which', status: true});
    this.words.push({name: 'people', status: true});
    this.words.push({name: 'thought', status: true});
    this.words.push({name: 'religious', status: true});
    this.words.push({name: 'long', status: true});
    this.words.push({name: 'before', status: true});
    this.words.push({name: 'other', status: true});
    this.words.push({name: 'say', status: true});
    this.words.push({name: 'set', status: true});
    this.words.push({name: 'improve', status: true});
    this.words.push({name: 'participant', status: true});
    this.words.push({name: 'question', status: true});
    this.words.push({name: 'fish', status: true});
    this.words.push({name: 'send', status: true});
    this.words.push({name: 'probably', status: true});
    this.words.push({name: 'game', status: true});
    this.words.push({name: 'agency', status: true});
    this.words.push({name: 'large', status: true});
    this.words.push({name: 'feel', status: true});
    this.words.push({name: 'heart', status: true});
    this.words.push({name: 'wife', status: true});
    this.words.push({name: 'support', status: true});
    this.words.push({name: 'kid', status: true});
    this.words.push({name: 'such', status: true});
    this.words.push({name: 'contain', status: true});
    this.words.push({name: 'party', status: true});
    this.words.push({name: 'sea', status: true});
    this.words.push({name: 'son', status: true});
    this.words.push({name: 'read', status: true});
    this.words.push({name: 'perform', status: true});
    this.words.push({name: 'movement', status: true});
    this.words.push({name: 'tonight', status: true});
    this.words.push({name: 'apply', status: true});
    this.words.push({name: 'community', status: true});
    this.words.push({name: 'stand', status: true});
    this.words.push({name: 'pressure', status: true});
    this.words.push({name: 'little', status: true});
    this.words.push({name: 'statement', status: true});
    this.words.push({name: 'whether', status: true});
    this.words.push({name: 'will', status: true});
    this.words.push({name: 'operation', status: true});
    this.words.push({name: 'bit', status: true});
    this.words.push({name: 'lawyer', status: true});
    this.words.push({name: 'blood', status: true});
    this.words.push({name: 'receive', status: true});
    this.words.push({name: 'have', status: true});
    this.words.push({name: 'bar', status: true});
    this.words.push({name: 'black', status: true});
    this.words.push({name: 'road', status: true});
    this.words.push({name: 'bag', status: true});
    this.words.push({name: 'win', status: true});
    this.words.push({name: 'chair', status: true});
    this.words.push({name: 'door', status: true});
    this.words.push({name: 'night', status: true});
    this.words.push({name: 'administration', status: true});
    this.words.push({name: 'glass', status: true});
    this.words.push({name: 'upon', status: true});
    this.words.push({name: 'indeed', status: true});
    this.words.push({name: 'with', status: true});
    this.words.push({name: 'type', status: true});
    this.words.push({name: 'travel', status: true});
    this.words.push({name: 'unit', status: true});
    this.words.push({name: 'significant', status: true});
    this.words.push({name: 'easy', status: true});
    this.words.push({name: 'man', status: true});
    this.words.push({name: 'task', status: true});
    this.words.push({name: 'another', status: true});
    this.words.push({name: 'red', status: true});
    this.words.push({name: 'network', status: true});
    this.words.push({name: 'make', status: true});
    this.words.push({name: 'line', status: true});
    this.words.push({name: 'small', status: true});
    this.words.push({name: 'spend', status: true});
    this.words.push({name: 'state', status: true});
    this.words.push({name: 'front', status: true});
    this.words.push({name: 'adult', status: true});
    this.words.push({name: 'mother', status: true});
    this.words.push({name: 'investment', status: true});
    this.words.push({name: 'over', status: true});
    this.words.push({name: 'full', status: true});
    this.words.push({name: 'dinner', status: true});
    this.words.push({name: 'budget', status: true});
    this.words.push({name: 'town', status: true});
    this.words.push({name: 'open', status: true});
    this.words.push({name: 'gun', status: true});
    this.words.push({name: 'dead', status: true});
    this.words.push({name: 'again', status: true});
    this.words.push({name: 'share', status: true});
    this.words.push({name: 'behavior', status: true});
    this.words.push({name: 'Mrs', status: true});
    this.words.push({name: 'use', status: true});
    this.words.push({name: 'smile', status: true});
    this.words.push({name: 'around', status: true});
    this.words.push({name: 'measure', status: true});
    this.words.push({name: 'cover', status: true});
    this.words.push({name: 'author', status: true});
    this.words.push({name: 'never', status: true});
    this.words.push({name: 'guy', status: true});
  }
}
